version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
    ports:
      - "3506:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/database.sql:/docker-entrypoint-initdb.d/database.sql  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 40s
      retries: 10

  backend:
    build: ./backend
    container_name: flask_api
    restart: always
    depends_on:
      db:
        condition: service_healthy  
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      DATABASE_URL: mysql+pymysql://root:rootpassword@db:3306/db  
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend  
    container_name: angular_app
    restart: always
    working_dir: /app
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    environment:
      - API_URL=http://backend:5000


volumes:
  db_data:
